### PR TITLE
Use SPDX-standard license naming

### PR DESCRIPTION
**Pull request by prescod**
It's not entirely clear what license you intended to use, so I offer this pull request to clarify.

References:

http://spdx.org/licenses/BSD-3-Clause

http://spdx.org/licenses/

### CODE REVIEW

**Comment by jprichardson** [comment]
Why? This feels like borderline pedantry. Who is `spdx.org` and why should one care? Is `BSD3` vs `BSD3-clause` really that ambiguous?

**Comment by prescod** [comment]
There are two different licenses that could be referred to as "BSD3". 

http://spdx.org/licenses/BSD-3-Clause

http://spdx.org/licenses/BSD-3-Clause-Clear

I literally don't know which one you meant, so I don't think it is pedantry. I actually thought at first that you meant something like "BSD Version 3."

SPDX is the Linux Foundation. These identifiers are used in a few places:

http://choosealicense.com/licenses/bsd-3-clause/

package.json is a machine-readable format so it only makes sense to try to make the values as machine-readable as the keys where possible. Machine-readable values requires standards, and SPDX produces that standard.

My particular use-case is because my corporation requires us to list and collect all of the licenses. Even startups require this if they are going through a corporate due-diligence process before investment. Because your repository uses a non-standard license syntax, I have to research which license you "really" meant rather than having my software just add your package to a list of packages using "BSD-3-Clause" license.

**Comment by jprichardson** [comment]
Ok fair enough. Thanks. Let me do a double-check and review.

**Comment by jprichardson** [comment]
Thanks again :)

**Pull request merged**
